name: PT_Finetuning
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2023.11.17=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_4
  - libgomp=13.2.0=h807b86a_4
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.44.2=h2797004_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4=h59595ed_2
  - openssl=3.2.0=hd590300_1
  - pip=23.3.2=pyhd8ed1ab_0
  - python=3.8.18=hd12c33a_1_cpython
  - readline=8.2=h8228510_1
  - setuptools=69.0.3=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - absl-py==2.1.0
      - aiofiles==23.2.1
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - altair==5.2.0
      - annotated-types==0.6.0
      - anyio==4.2.0
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - backcall==0.2.0
      - cachetools==5.3.2
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - decorator==5.1.1
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastapi==0.109.0
      - ffmpy==0.3.1
      - filelock==3.13.1
      - fire==0.5.0
      - fonttools==4.47.2
      - frozenlist==1.4.1
      - fsspec==2023.12.2
      - google-auth==2.27.0
      - google-auth-oauthlib==1.0.0
      - gradio==4.8.0
      - gradio-client==0.7.1
      - grpcio==1.60.0
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - huggingface-hub==0.20.3
      - idna==3.6
      - importlib-metadata==7.0.1
      - importlib-resources==6.1.1
      - ipython==8.12.3
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.3.2
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - lightning-utilities==0.10.1
      - markdown==3.5.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.4
      - matplotlib==3.7.4
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - multidict==6.0.4
      - munch==2.5.0
      - numpy==1.24.4
      - oauthlib==3.2.2
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.9.0.80
      - orjson==3.9.12
      - packaging==23.2
      - pandas==2.0.3
      - parso==0.8.3
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.1.0
      - pkgutil-resolve-name==1.3.10
      - prompt-toolkit==3.0.43
      - protobuf==3.20.1
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pydantic==2.6.0
      - pydantic-core==2.16.1
      - pydub==0.25.1
      - pygments==2.17.2
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-multipart==0.0.6
      - pytorch-lightning==1.9.0
      - pytorchwildlife==1.0.1.1
      - pytz==2023.4
      - pyyaml==6.0.1
      - referencing==0.33.0
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rich==13.7.0
      - rpds-py==0.17.1
      - rsa==4.9
      - scikit-learn==1.2.0
      - scipy==1.10.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - six==1.16.0
      - sniffio==1.3.0
      - stack-data==0.6.3
      - starlette==0.35.1
      - supervision==0.16.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.2.0
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch==1.10.1
      - torchaudio==0.10.1
      - torchmetrics==1.3.0.post0
      - torchvision==0.11.2
      - tqdm==4.66.1
      - traitlets==5.14.1
      - typer==0.9.0
      - typing-extensions==4.9.0
      - tzdata==2023.4
      - ultralytics-yolov5==0.1.1
      - urllib3==2.2.0
      - uvicorn==0.27.0.post1
      - wcwidth==0.2.13
      - websockets==11.0.3
      - werkzeug==3.0.1
      - yarl==1.9.4
      - zipp==3.17.0
prefix: /home/andreshernandezcelisadeccoc/.conda/envs/PT_Finetuning
